version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./Blood-Bank-Management-System:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
    php:
        image: php:7-fpm
        volumes:
            - ./Blood-Bank-Management-System:/code
        build:
            context: ./php
            dockerfile: Dockerfile
    db:
        image: mysql:latest
        ports:
            - "9906:3306"
        environment:
            MYSQL_DATABASE: bloodbank
            MYSQL_ROOT_PASSWORD: blood_pass
        volumes:
            - ./Blood-Bank-Management-System/sql/bloodbank.sql:/bloodbank.sql
